language: objective-c
osx_image: xcode10

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - PROJECT_NAME="Marshal"
    - PROJECT_SUFFFIX=".xcodeproj"
    - FRAMEWORK_SCHEME="Marshal"
    - IOS_SDK=iphonesimulator10.0
    - TVOS_SDK=appletvsimulator9.2
    - OSX_SDK=macosx10.11
  matrix:
    - DESTINATION="OS=8.0,name=iPhone 4S"       SCHEME="$FRAMEWORK_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="OS=8.1,name=iPhone 4S"       SCHEME="$FRAMEWORK_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="OS=8.2,name=iPhone 5"        SCHEME="$FRAMEWORK_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="OS=8.3,name=iPhone 5S"       SCHEME="$FRAMEWORK_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="OS=8.4,name=iPad Air"        SCHEME="$FRAMEWORK_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="OS=9.0,name=iPhone 6S Plus"  SCHEME="$FRAMEWORK_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="OS=9.1,name=iPhone 6S"       SCHEME="$FRAMEWORK_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="OS=9.3,name=iPad Pro"        SCHEME="$FRAMEWORK_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="OS=10.0,name=iPhone 7"       SCHEME="$FRAMEWORK_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="OS=11.0,name=iPhone X"       SCHEME="$FRAMEWORK_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="OS=12.0,name=iPhone X"       SCHEME="$FRAMEWORK_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="arch=x86_64"                 SCHEME="$FRAMEWORK_SCHEME" SDK="$OSX_SDK"

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -project "$PROJECT_NAME$PROJECT_SUFFFIX" -scheme "$SCHEME" -sdk "$SDK" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash) -J "$PROJECT_NAME"

notifications:
  email: false
